language: objective-c
compiler:
- clang
before_install:
- sudo brew update
- sudo brew install qt
- sudo brew install openssl

before_script:
- cd ./redis-desktop-manager
- sudo chmod 777 configure
- ./configure
script: 
  - qmake -qt=qt5 -v
  - qmake -qt=qt5
  - make clean
  - make -s
  - cd ./../tests/
  - qmake
  - make clean
  - make -s
  - ./../bin/tests/tests -platform minimal -txt
services:
  - redis-server
notifications:
  recipients:
    - u.glide@gmail.com
  email:
    on_success: change
    on_failure: always
