language: objective-c
compiler:
- clang
before_install:
- brew update
- brew install qt5
- brew install openssl
- brew install libssh2
script: 
  - qmake -qt=qt5 -v
  - qmake -qt=qt5
  - make clean
  - make -s
  - cd ./../tests/
  - qmake
  - make clean
  - make -s
  - ./../bin/tests/tests -platform minimal -txt
services:
  - redis-server
notifications:
  recipients:
    - u.glide@gmail.com
  email:
    on_success: change
    on_failure: always
