language: cpp
compiler:
  - gcc
before_install:
- sudo bash ./build/start_ssh_server.sh
- sudo add-apt-repository --yes ppa:beineri/opt-qt55
- sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test 
- sudo apt-get update -qq
- sudo apt-get install qt55base qt55imageformats qt55tools libssl1.0.0 libssh2-1-dev gdb  -y -qq
- sudo apt-get install gcc-4.9 g++-4.9 -y -qq
- sudo rm -f /usr/bin/gcc
- sudo rm -f /usr/bin/g++
- sudo rm -f /usr/bin/gcov
- sudo ln -s /usr/bin/gcc-4.9 /usr/bin/gcc
- sudo ln -s /usr/bin/g++-4.9 /usr/bin/g++
- sudo ln -s /usr/bin/gcov-4.9 /usr/bin/gcov
- source /opt/qt55/bin/qt55-env.sh
- sudo pip install cpp-coveralls
- uname -m
- gcc --version
- qmake -v
script: 
  - cd ./tests
  - qmake DEFINES+=INTEGRATION_TESTS
  - make -s -j 2
  - ./../bin/tests/tests -platform minimal -txt
  - ./../bin/tests/qml_tests -platform minimal -txt
  - cd ./../src
  - sudo chmod a+x configure
  - ./configure
  - qmake
  - make -s -j 2
after_success:
  - cd ./../tests
  - coveralls -b `pwd`/unit_tests/ -r `readlink -m ./../` -e 3rdparty/ -e tests/ -E .+/moc_.* -E .+/qrc_.* -E .+/qxt.* -E .+/ui_.*  > coveralls.log
services:
  - redis-server
notifications:
  recipients:
    - u.glide@gmail.com
  email:
    on_success: change
    on_failure: change
