language: cpp
os:
  - linux
  - osx
before_install:
- sudo pip install cpp-coveralls
- cd ./src && ./configure && cd ./../
- qmake -v
script:
  - git submodule update --init --recursive 
  - cd ./tests
  - qmake DEFINES+=INTEGRATION_TESTS && make -s -j 2
  - ./../bin/tests/tests -platform minimal -txt
  - ./../bin/tests/qml_tests -platform minimal -txt
  - cd ./../src
  - qmake && make -s -j 2
after_success:
  - cd ./../tests
  - coveralls -b `pwd`/unit_tests/ -r `readlink -m ./../` -e 3rdparty/ -e tests/ -E .+/moc_.* -E .+/qrc_.* -E .+/qxt.* -E .+/ui_.*  > coveralls.log
services:
  - redis-server
notifications:
  recipients:
    - u.glide@gmail.com
  email:
    on_success: change
    on_failure: change
