language: cpp
compiler:
  - gcc
before_install:
- sudo add-apt-repository --yes ppa:beineri/opt-qt511
- sudo apt-get update -qq
- sudo apt-get install qt51base qt51imageformats qt51tools qt51xmlpatterns qt51x11extras -y -qq
- uname -m
- export QTDIR=/opt/qt51
- export PATH=$QTDIR/bin:$PATH
- export LD_LIBRARY_PATH=$QTDIR/lib/:$QTDIR/lib/`uname -m`-linux-gnu:$LD_LIBRARY_PATH
- sudo apt-get install libssl1.0.0 -y -qq
- sudo apt-get install gdb -y -qq
- sudo sh ./vagrant-provision/build_automake.sh
before_script:
- cd ./redis-desktop-manager
- sudo chmod 777 configure
- ./configure
script: 
  - qmake -v
  - qmake
  - make -s
  - cd ./../crashreporter/
  - qmake
  - make -s
  - cd ./../tests/
  - qmake
  - make -s
  - ./../bin/tests/tests -platform minimal -txt
after_success:
  - sudo pip install cpp-coveralls --use-mirrors
  - cp -Rf ./../redis-desktop-manager/include ./
  - cp -Rf ./../redis-desktop-manager/source ./
  - coveralls --no-gcov --build-root './../bin/tests/obj/'  --exclude deps
services:
  - redis-server
notifications:
  recipients:
    - u.glide@gmail.com
  email:
    on_success: change
    on_failure: always