language: cpp
compiler:
  - gcc
env:
  global:
  - secure: "R7RcjQGpxQsGFdvIGhvZo7TgmUwVMdus0FOmuT+D0eGs2ins8CckONZwDFpib27BmMaw55V+LRobWs+4nkflYidr/Kyp9aZfy1Hc7PFMLcURz4pxz1B0Tb8fNx4xYwIyOvVZcWeGbDyYDvwLeomNH6GqAOiSi4DZjLDHnKJETo8="
before_install:
- sudo add-apt-repository --yes ppa:beineri/opt-qt54
- sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test 
- sudo apt-get update -qq
- sudo apt-get install qt54base qt54imageformats qt54tools qt54xmlpatterns -y -qq
- uname -m
- export QTDIR=/opt/qt54
- export PATH=$QTDIR/bin:$PATH
- export LD_LIBRARY_PATH=$QTDIR/lib/:$QTDIR/lib/`uname -m`-linux-gnu:$LD_LIBRARY_PATH
- sudo apt-get install libssl1.0.0 libssh2-1-dev -y -qq
#- sudo sh ./build/build_automake.sh
- sudo apt-get install gcc-4.7 g++-4.7 gdb -y -qq
- sudo rm -f /usr/bin/gcc
- sudo rm -f /usr/bin/g++
- sudo rm -f /usr/bin/gcov
- sudo ln -s /usr/bin/gcc-4.7 /usr/bin/gcc
- sudo ln -s /usr/bin/g++-4.7 /usr/bin/g++
- sudo ln -s /usr/bin/gcov-4.7 /usr/bin/gcov
- sudo pip install cpp-coveralls --use-mirrors
before_script:
- cd ./src
script: 
  - cd ./../tests
  - qmake -v
  - qmake DEFINES+=INTEGRATION_TESTS
  - make -s -j 2
  - ./../bin/tests/tests -platform minimal -txt
  - coveralls -b `pwd` -r `readlink -m ./../` -e 3rdparty/ -e tests/ -E .+/moc_.* -E .+/qrc_.*
  - cd ./../src
  - sudo chmod a+x configure
  - sudo ./configure
  - qmake
  - make -s -j 2
services:
  - redis-server
notifications:
  recipients:
    - u.glide@gmail.com
  email:
    on_success: change
    on_failure: change
addons:
  coverity_scan:
    project:
      name: "uglide/RedisDesktopManager"
      description: "Build submitted via Travis CI"
    notification_email: u.glide@gmail.com
    build_command_prepend: "./configure; qmake"
    build_command:  "make -j 2"
    branch_pattern: "0.8.0"   
